<?xml version="1.0" ?>
<testsuite name="CalcTest-20191207101041" tests="2" time="0.000" failures="0" errors="1">
	<testcase classname="CalcTest" name="test_add" time="0.000"/>
	<testcase classname="CalcTest" name="test_add1" time="0.000">
		<error type="AssertionError" message="2 != 3"><![CDATA[Traceback (most recent call last):
  File "flask_rest/tests/test.py", line 12, in test_add1
    self.assertEqual(2,self.calc.add())
AssertionError: 2 != 3
]]></error>
	</testcase>
	<system-out><![CDATA[]]></system-out>
	<system-err><![CDATA[]]></system-err>
</testsuite>
